inherits = "default"

"ui.background" = {}

"ui.selection.primary" = { bg = "#ff9e64", fg = "#000000" }

"ui.cursor" = { bg = "#ffffff", fg = "#000000" }
"ui.cursor.primary.select" = { bg = "#ffffff", fg = "#000000" }
